### ISSUE TITLE
Always socket hang up after 60 seconds

### ISSUE THREAD

**Issue by Walter-meng** [TimonKK/clickhouse#117]
when perform some long time query, it will show after 60 seconds
`Error: socket hang up
    at connResetException (internal/errors.js:612:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}`

even i set session timeout to 120 s and     isSessionPerQuery:true

**Comment by mike-luabase** [comment]
@Walter-meng did you find a way around this?

**Comment by mike-luabase** [comment]
@TimonKK we are hitting this to
