### ISSUE TITLE
"data.every is not a function" error

### ISSUE THREAD

**Issue by SEA99** [TimonKK/clickhouse#128]

**Comment by SEA99** [comment]
Exception has occurred: TypeError: data.every is not a function
  at QueryCursor._getReqParams (/home/sea/src/bi/invest/etl-tinkoff-refs/node_modules/clickhouse/index.js:555:23)
    at QueryCursor.exec (/home/sea/src/bi/invest/etl-tinkoff-refs/node_modules/clickhouse/index.js:597:24)

call:
await ch.query('insert into test1 (id,name) values({id:UInt32},{name:String}) ', { params: { name:'xxx', id:123 } } ).toPromise();
  ;

**Comment by SEA99** [comment]
думаю такая правка https://github.com/TimonKK/clickhouse/compare/master...SEA99:clickhouse:master
