### ISSUE TITLE
ws.writeRow -  Error: 500: Internal Server Error

### ISSUE THREAD

**Issue by neyy91** [TimonKK/clickhouse#27]
Good time of day. When using the ws.writeRow method - I get an error - Error: 500: Internal Server Error.

1) so I'm creating a table

CREATE TABLE visits2 (  id UInt64,  duration Int64 ) ENGINE = MergeTree()  PRIMARY KEY id  ORDER BY id;

2) I'm just checking the record with the usual request - everything works, records

INSERT INTO test.visits2 VALUES (1, 10)

3) Now I want to record a lot of things in one go, and most importantly, quickly. From the tests I take your method to prepare a request, fill it with my own data

      const ws = clickhouse.insert('INSERT INTO test.visits2').stream();
      let count = 0;
      let rowCount = 50
      for(let i = 1; i <= rowCount; i++) {
        await ws.writeRow(
          [
            _.range(0, 50).map(
              j => `${i}:${j}`
            ).join('-')
          ]
        );
        ++count;
      }

the value will be about this ---  43:0-43:1-43:2-43:3-43:4-43:5-43:6-43:7-43:8-43:9.......

4) //wait stream finish
const result = await ws.exec();

5) and I'm getting a server error.

 Error: 500: Internal Server Error
    at getErrorObj (/****/backend/node_modules/clickhouse/index.js:107:12)
    at Request.<anonymous> (/****/backend/node_modules/clickhouse/index.js:205:7)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/****/backend/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)

6)  If I've made a mistake in query, can I get an example ? Thank you

**Comment by TimonKK** [comment]
Hi,
You tried insert String to column with Integer type. And missed second column

**Comment by neyy91** [comment]
Yes, thx
