### ISSUE TITLE
Async iterator not working

### ISSUE THREAD

**Issue by tobia** [TimonKK/clickhouse#72]
**Steps to reproduce**

package.json
```
{
  "dependencies": {
    "clickhouse": "^2.2.1"
  }
}
```

test.js
```
const { ClickHouse } = require('clickhouse')

const CH = new ClickHouse({ url: 'http://127.0.0.1:8123/' })

async function main() {
  for await (const row of CH.query('select 1+1 as two').stream()) {
    console.log(row.two)
  }
  console.log('done')
}

main()
```

Run `npm i` and then `node test.js`

**Expected results**

```
2
done
```

**Actual results**

```
2
/tmp/asyncbug/node_modules/stream2asynciter/index.js:17
					this.close();
					     ^

TypeError: this.close is not a function
    at Readable.destroy [as _destroy] (/tmp/asyncbug/node_modules/stream2asynciter/index.js:17:11)
    at Readable.destroy (internal/streams/destroy.js:39:8)
    at endReadableNT (internal/streams/readable.js:1343:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I'm using node v14.16.0 and npm 6.14.11 if it matters.

**Comment by TimonKK** [comment]
Hi& please update lib to lastest 2.2.4

**Comment by tobia** [comment]
Oops, sorry.
